version: '3'
services:
  app:
    build: .
    depends_on:
      - selenium
    stdin_open: true
    tty: true
    environment:
      EMAIL: "${EMAIL}"
      PASSWORD: "${PASSWORD}"
    command:
      /app/wait-for-it.sh http://selenium:4444/wd/hub -t 25 -- python main.py ${EMAIL} ${PASSWORD}

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - '4444:4444'
    shm_size: 2g
